# Generated by Django 2.0.3 on 2018-03-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20180320_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='my_app.Category'),
        ),
    ]
